--- #YAML:1.0
name:                CPAN-Test-Dummy-Perl5-Make
version:             1.03
abstract:            CPAN Test Dummy for CPAN.pm
license:             unknown
generated_by:        ExtUtils::MakeMaker version 6.30_04
author:              ~
distribution_type:   module
requires:     
meta-spec:
    url: http://module-build.sourceforge.net/META-spec-new.html
    version: 1.1
